#!/bin/bash

RUN_DIR=/var/vcap/sys/run/tvheadend
LOG_DIR=/var/vcap/sys/log/tvheadend
STORE_DIR=/var/vcap/store/tvheadend
PIDFILE=${RUN_DIR}/tvheadend.pid

source /var/vcap/packages/python-2.7/bosh/runtime.env

case $1 in

  start)
    mkdir -p $RUN_DIR $LOG_DIR
    chown -R vcap:vcap $RUN_DIR $LOG_DIR

    # Looks like TVHeadend looks at HOME directory as a start...
    # See https://github.com/tvheadend/tvheadend/blob/release/4.2/src/dvr/dvr_config.c#L283
    export HOME=${STORE_DIR}/videos

    cd /var/vcap/packages/tvheadend
    bin/tvheadend \
        --user vcap \
        --group vcap \
        --firstrun \
        --fork \
        --config ${STORE_DIR} \
        --pid ${PIDFILE} \
        >> ${LOG_DIR}/stdout.log \
        2>> ${LOG_DIR}/stderr.log

    ;;

  stop)
    kill $(cat ${PIDFILE})
    rm -f ${PIDFILE}

    ;;

  *)
    echo "Usage: ctl {start|stop}" ;;

esac
