#!/bin/bash

set -eu

TVHEADEND_BASE=/var/vcap/store/tvheadend
RUN_DIR=/var/vcap/sys/run/tvheadend
LOG_DIR=/var/vcap/sys/log/tvheadend
mkdir -p ${RUN_DIR} ${LOG_DIR} ${TVHEADEND_BASE}/videos
chown -R vcap:vcap ${RUN_DIR} ${LOG_DIR} ${TVHEADEND_BASE} ${TVHEADEND_BASE}/videos
