#!/bin/bash

set -eu

export TVHEADEND_BASE=/var/vcap/store/tvheadend

mkdir -p ${TVHEADEND_BASE}/videos
id -u tvheadend || useradd -d ${TVHEADEND_BASE}/videos -s /usr/sbin/nologin -G vcap tvheadend

chown tvheadend:vcap ${TVHEADEND_BASE} ${TVHEADEND_BASE}/videos

